---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mlflow
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
{{- if .Values.route.host }}
  host: {{ .Values.route.host }}
{{- end}}
  to:
    kind: Service
    name: mlflow
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
